SELECT DISTINCT A.DATAINCLUSAO AS DATA_INCLUSAO_SOL_PAI,
EMP.NOME AS NOME_EMPRESA,
FIL.NOME AS NOME_FILIAL,

CASE WHEN A.STATUS = 1 THEN 'CADASTRADA' ELSE
   CASE WHEN A.STATUS = 2 THEN 'CONFIRMADA' ELSE
       CASE WHEN A.STATUS = 3 THEN 'EM ATENDIMENTO' ELSE
          CASE WHEN A.STATUS = 4 THEN 'ENCERRADA' ELSE
             CASE WHEN A.STATUS = 5 THEN 'RECUSADA' ELSE
                CASE WHEN A.STATUS = 6 THEN 'CANCELADA' ELSE 'ATENDIMENTO DIVERGENTE'
                END
             END
          END
       END
   END
END AS STATUS_SOL_PAI,

CASE WHEN SOL_ITENS.STATUS = 1 THEN 'CADASTRADA' ELSE
   CASE WHEN SOL_ITENS.STATUS = 2 THEN 'ATENDIMENTO DIVERGENTE' ELSE
       CASE WHEN SOL_ITENS.STATUS = 3 THEN 'EM ATENDIMENTO' ELSE
          CASE WHEN SOL_ITENS.STATUS = 4 THEN 'ENCERRADA' ELSE
             CASE WHEN SOL_ITENS.STATUS = 5 THEN 'CANCELADA'
             END
          END
       END
   END
END AS STATUS_SOL_FILHO,

CASE WHEN A.MODALIDADE = 'R' THEN 'REGULARIZAÇÃO' ELSE
    CASE WHEN A.MODALIDADE = 'C' THEN 'CATALOGO' ELSE 'NORMAL' END
END AS MODALIDADE,
A.NUMERO AS NUM_SOL_PAI,
SOL_ITENS.NUMERO AS NUM_SOL_FILHO,
OCS.NUMERO AS ORDEM_DE_COMPRA,
UPPER(SOL.APELIDO) AS NOME_DO_SOLICITANTE,
UPPER(SOL.EMAIL) AS EMAIL_DO_SOLICITANTE,

CASE WHEN UPPER(SOL_APROVA.APELIDO) IS NOT NULL THEN UPPER(SOL_APROVA.APELIDO) ELSE
UPPER(APR.APELIDO) END AS NOME_DO_APROVADOR,
CASE WHEN UPPER(SOL_APROVA.EMAIL) IS NOT NULL THEN UPPER(SOL_APROVA.EMAIL) ELSE
UPPER(APR.EMAIL) END AS EMAIL_DO_APROVADOR,

REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.MOTIVOSTATUS ,char(13),''),char(9),''),char(10),''),'/N','/ N'),'/R','/ R') AS MOTIVO_STATUS,

SOL_ITENS.QUANTIDADE AS QUANTIDADE_SOLICITADA,
SOL_ITENS.VALORESTIMADO AS VALOR_DO_ITEM,
RA.CODIGO AS CENTRO_DE_CUSTO,
CASE WHEN SOL_ITENS.PROJETO IS NULL THEN 'OPEX' ELSE
'CAPEX' END AS PROJETO,
CONCAT(FIN.ESTRUTURA,' - ',FIN.CODIGO) AS FINALIDADE_ESTRUTURA,
FIN.DESCRICAO AS FINALIDADE_DESCRICAO,


REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(A.OBSERVACOES ,char(13),''),char(9),''),char(10),''),'/N','/ N'),'/R','/ R') AS TEXTO_OBSERVACOES,
REPLACE(REPLACE(REPLACE(REPLACE(REPLACE(AC.NOME ,char(13),''),char(9),''),char(10),''),'/N','/ N'),'/R','/ R') AS NOME_ITEM,
EA.NOME AS UNIDADE_DE_MEDIDA

FROM CP_SOLICITACOES A
LEFT JOIN EMPRESAS EMP ON EMP.HANDLE = A.EMPRESA
LEFT JOIN FILIAIS FIL ON FIL.HANDLE = A.FILIAL
LEFT JOIN Z_GRUPOUSUARIOS SOL ON SOL.HANDLE = A.SOLICITANTE
LEFT JOIN Z_GRUPOUSUARIOS APR ON APR.HANDLE = A.USUARIOALTERACAO
LEFT JOIN CP_SOLICITACAOITENS SOL_ITENS ON SOL_ITENS.SOLICITACAO = A.HANDLE
LEFT JOIN PD_PRODUTOS AC ON AC.HANDLE = SOL_ITENS.PRODUTO
INNER JOIN CM_UNIDADESMEDIDA EA ON  EA.HANDLE = AC.UNIDADEMEDIDACOMPRAS
LEFT JOIN CP_FINALIDADES FIN ON FIN.HANDLE = SOL_ITENS.FINALIDADE
LEFT JOIN CT_CC RA ON RA.HANDLE = SOL_ITENS.CENTROCUSTO
LEFT JOIN (SELECT * FROM CP_SOLICITACAOHISTORICO WHERE DESCRICAO = 'Aguardando aprovação') SOL_HIST ON SOL_HIST.SOLICITACAO = A.HANDLE
LEFT JOIN Z_GRUPOUSUARIOS SOL_APROVA ON SOL_APROVA.HANDLE=SOL_HIST.USUARIO
LEFT JOIN CP_ORDENSCOMPRA OCS ON OCS.NUMERODOCUMENTOORIGEM = A.NUMERO
WHERE A.NUMERO IN ("359074","359624","360512","359438","360679","359051","359033","359257","358972","358565","358567","358569","359813","359538","359468","359221","358604","360097","350867","358287","358599","358298","358576","358795","355569","359956")
